apiVersion: v1
kind: Service
metadata:
  name: inference-api
  namespace: mlops
  labels:
    app: inference-api
  annotations:
    # AWS NLB for low-latency GPU inference traffic
    service.beta.kubernetes.io/aws-load-balancer-type:            "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme:          "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: inference-api
  ports:
    - name:       http
      protocol:   TCP
      port:       80
      targetPort: 8080
